version: '3.8'

services:
  db:
    image: postgis/postgis:13-3.1
    container_name: postgis
    environment:
      POSTGRES_DB: route_smart_db
      POSTGRES_USER: routesmart_app
      POSTGRES_PASSWORD: app_password
    ports:
        - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: route-smart-app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/routesmart_app
      SPRING_DATASOURCE_USERNAME: routesmart_app
      SPRING_DATASOURCE_PASSWORD: app_password
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
